grabbedBubble = noone;
moveMult = 0.1;
pushMult = 0.3;
multY = 3;
maxPower = 7;
hitboxBuffer = 4;
powerX = 0;
powerY = 0;
sensitivity = 0.2;
maxDist = 10;
falloffRate = 0.4;
extraDistance = 50;
birdIdealX = 0;
birdIdealY = 0;
birdX = 0;
birdY = 0;
birdSpeed = 0.5;
birdIndex = sprCursor_click_nothing1;
birdInst = true;
image_alpha = 0;
//maxDist = 0;
event_inherited();

