xVel = 0
yVel = 0
maxDistX = 0
maxDistY = 0
maxDist = 24 + sprite_width;
shotSpeed = 1
roomRight = room_width;
roomBottom = room_height;
roomMiddleX = room_width/2;
roomMiddleY = room_width/2;
roomPadding = sprite_width;
killTimer = 0;
killTimeMax = 50